### ISSUE TITLE
Further information about Factory method Design Pattern

### ISSUE THREAD

**Issue by alexdenisdev** [KevinTopollaj/Design-Patterns-in-iOS#1]
Hello Kevin,

First of all, thank you for all your useful explanation about design patterns.

You mentioned that Factory Method _"Supports the Open-Closed Principle by allowing the addition of new subclasses without modifying the existing factory class."_.

However, if we add a new case `whatsApp`, we need to update our `enum` and `createMessageSender` method. So we need to update the existing Factory class.

Is this true or have I misunderstood something?

Thank you in advance for your help,

Alexandre

**Comment by KevinTopollaj** [comment]
Hello Alexandre, 

I am glad you found the explanation of the design patterns useful and thank you for the positive feedback!

Regarding your question about a positive aspect that I mentioned for the Factory Method that "`Supports the Open-Closed Principle by allowing the addition of new subclasses without modifying the existing factory class.`" I look a it like this:

We know that the Open-Closed principle states that software entities should be open for extension, but closed for modification.

In the example that you provided by creating a  new object `WhatsApp` that conforms to the `MessageSender` protocol, we need to update the `enum MessageType` to contain that new case `whatsApp`.

I see this as an extension of the types that the Factory class can support and not a modification to that class because the return will always be a `MessageSender` so we are not modifying the end result we are just extending its functionalities to support the creation of new objects.

All the best,

Kevin

**Comment by alexdenisdev** [comment]
Hello Kevin,
Thank you for your clear answer. I understand much better the O/C principles,
 
`Without modifying the existing factory class.` doesn't mean `"forbidden to modify the existing factory class".`  It rather means, not making changes that could lead to modifications for customers who use this factory.

That's right ?

Alexandre

**Comment by KevinTopollaj** [comment]
Hello Alexandre,

You're welcome, I am glad that my explanation helped you to better understand the O/C principles.

Yes, that was my intention when I implemented the Factory Design Pattern in this example so you will be able to extend it but that will not affect the other parts of your code that already use it.
